DETECTOR = "ORB"
MATCHER = "BF"
HOSTS_PATH = "../conf/known_hosts"
IMAGES_PATH = "../host_images/"
DETECTOR_FEATURES = 500
RELEVANT_FEATURES = 10
DISTANCE_THRESHOLD = 15
UNKNOWN_HOST = "UNKNOWN_HOST"
